// More Quiz Duel questions, merged into the bank in trivia.js. Same shape: [question, right, wrong, wrong, wrong].
// Music is current only (2024–2026 releases, charts and awards), checked against chart and awards listings in October 2026.

export const MUSIC = [
  ['Which artist released "Joy Is Coming", Nigeria’s No. 1 song of 2025?', 'Fido', 'Shallipopi', 'Chella', 'Kunmie'],
  ['"Jogodo", 2026’s longest-running No. 1 in Nigeria, is Asake and who?', 'Wizkid', 'Davido', 'Burna Boy', 'Rema'],
  ['Asake made "Worship" with which DJ?', 'DJ Snake', 'Calvin Harris', 'David Guetta', 'Black Coffee'],
  ['Who made "Chanel" featuring Asake in 2026?', 'Blaqbonez', 'Olamide', 'Odumodublvck', 'Ladipoe'],
  ['Davido’s "With You" features which singer?', 'Omah Lay', 'Fola', 'Ayra Starr', 'Chike'],
  ['What is the name of Davido’s 2025 album?', '5ive', 'Timeless', 'Morayo', 'Lungu Boy'],
  ['Which artist released the album "Morayo"?', 'Wizkid', 'Davido', 'Asake', 'Rema'],
  ['What is Burna Boy’s 2025 album called?', 'No Sign of Weakness', 'I Told Them...', 'Love, Damini', 'Twice as Tall'],
  ['Rema’s "Baby (Is It a Crime)" samples which singer?', 'Sade', 'Whitney Houston', 'Brandy', 'Lauryn Hill'],
  ['Which Rema song held No. 1 in Nigeria for 8 weeks in late 2025?', 'Fun', 'Calm Down', 'Hehehe', 'Azaman'],
  ['"Body (Danz)" featuring Mavo is by which artist?', 'CKay', 'Fireboy DML', 'Joeboy', 'Ruger'],
  ['Tyla won the 2026 Grammy for Best African Music Performance with which song?', 'Push 2 Start', 'Water', 'Jump', 'Art'],
  ['Who won Best African Music Performance at the 2025 Grammys with "Love Me JeJe"?', 'Tems', 'Ayra Starr', 'Tyla', 'Yemi Alade'],
  ['"Raindance" is Dave featuring which singer?', 'Tems', 'Ayra Starr', 'Tiwa Savage', 'Simi'],
  ['Who won Album of the Year at the 2026 Grammys?', 'Bad Bunny', 'Taylor Swift', 'Lady Gaga', 'Sabrina Carpenter'],
  ['"Luther" won Record of the Year at the 2026 Grammys. Who sings it with Kendrick Lamar?', 'SZA', 'Rihanna', 'Doja Cat', 'Summer Walker'],
  ['Who won Best New Artist at the 2026 Grammys?', 'Olivia Dean', 'Chappell Roan', 'Benson Boone', 'Gracie Abrams'],
  ['Which Billie Eilish song won Song of the Year at the 2026 Grammys?', 'Wildflower', 'Birds of a Feather', 'Lunch', 'Chihiro'],
  ['Who sings "Messy", the 2026 Grammy winner for Best Pop Solo Performance?', 'Lola Young', 'Olivia Rodrigo', 'Gracie Abrams', 'Tate McRae'],
  ['Which Taylor Swift album came out on 3 October 2025?', 'The Life of a Showgirl', 'The Tortured Poets Department', 'Midnights', 'Lover'],
  ['Who features on Taylor Swift’s song "The Life of a Showgirl"?', 'Sabrina Carpenter', 'Olivia Rodrigo', 'Lana Del Rey', 'Ed Sheeran'],
  ['Whose "Choosin’ Texas" spent a record-tying 22 weeks at No. 1 in the US in 2026?', 'Ella Langley', 'Morgan Wallen', 'Shaboozey', 'Lainey Wilson'],
  ['Billboard’s No. 1 song of 2025, "Die with a Smile", is Lady Gaga and who?', 'Bruno Mars', 'The Weeknd', 'Bradley Cooper', 'Post Malone'],
  ['Rosé, who made "APT." with Bruno Mars, is from which group?', 'Blackpink', 'Twice', 'NewJeans', 'Aespa'],
  ['Who sings "Pink Pony Club"?', 'Chappell Roan', 'Sabrina Carpenter', 'Gracie Abrams', 'Reneé Rapp'],
  ['Who sings "Ordinary", a top 10 song of 2025 in the US?', 'Alex Warren', 'Benson Boone', 'Teddy Swims', 'Noah Kahan'],
  ['Who headlined the Super Bowl halftime show in February 2025?', 'Kendrick Lamar', 'Drake', 'Eminem', 'Usher'],
  ['Who headlined the Super Bowl halftime show in February 2026?', 'Bad Bunny', 'Kendrick Lamar', 'Taylor Swift', 'Beyoncé'],
  ['Which 2025 No. 1 brought together Olamide, Seyi Vibez, Asake and Young Jonn?', '99', 'Ewo', 'Laho', 'Cash Flow'],
  ['Young Jonn’s "Cash Flow" (2025) features which star?', 'Wizkid', 'Davido', 'Burna Boy', 'Asake'],
  ['"LaLaLa", a No. 1 in December 2025, is Young Jonn and who?', 'Rema', 'Omah Lay', 'Fireboy DML', 'Kizz Daniel'],
  ['Who sings "Waist" (2025)?', 'Omah Lay', 'Ruger', 'Bnxn', 'Victony'],
  ['Whose "My Darling" was the only Nigerian song on TikTok’s global year-end chart for 2025?', 'Chella', 'Fido', 'Kunmie', 'Shallipopi'],
  ['Who made "Laho"?', 'Shallipopi', 'Seyi Vibez', 'Zerrydl', 'Poco Lee'],
  ['"Arike" held No. 1 in Nigeria for five weeks in 2025. Whose song is it?', 'Kunmie', 'Fido', 'Chella', 'Young Jonn'],
  ['Which Seyi Vibez song hit No. 1 in Nigeria in February 2025?', 'Shaolin', 'Pressure', 'Chance', 'Different Pattern'],
  ['Fola’s "Treat U Right" (2026) features which singer?', 'Ayra Starr', 'Tems', 'Tiwa Savage', 'Qing Madi'],
  ['Who made "Paparazzi" with Fola?', 'Shoday', 'Shallipopi', 'Fido', 'Kunmie'],
  ['"Back Outside" (2026) is Bnxn with which producer?', 'Sarz', 'Pheelz', 'Kel-P', 'Rexxie'],
  ['"Who’s Dat Girl" is Ayra Starr with which artist?', 'Rema', 'Wizkid', 'Burna Boy', 'Asake'],
  ['Asake made "Badman Gangsta" with which French rapper?', 'Tiakola', 'Gims', 'Ninho', 'Niska'],
  ['Which Burna Boy song spent four weeks at No. 1 in Nigeria in 2025?', 'Love', 'Higher', 'Last Last', 'City Boys'],
];

export const MORE = {
  general: [
    ['What is the smallest prime number?', '2', '1', '3', '0'],
    ['How many days are in a leap year?', '366', '365', '364', '367'],
    ['Which bird is a symbol of peace?', 'Dove', 'Eagle', 'Parrot', 'Owl'],
    ['How many strings does a standard guitar have?', '6', '4', '5', '7'],
    ['What is the largest mammal?', 'Blue whale', 'Elephant', 'Giraffe', 'Hippo'],
    ['What is a baby cat called?', 'Kitten', 'Cub', 'Pup', 'Calf'],
    ['How many letters are in the English alphabet?', '26', '24', '25', '28'],
    ['Which planet is famous for its rings?', 'Saturn', 'Mars', 'Mercury', 'Venus'],
    ['How many legs does a spider have?', '8', '6', '10', '12'],
    ['What colour is an emerald?', 'Green', 'Red', 'Blue', 'Purple'],
    ['What is the main language of Brazil?', 'Portuguese', 'Spanish', 'English', 'French'],
    ['Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Pablo Picasso', 'Vincent van Gogh'],
    ['How many zeros are in one million?', '6', '5', '7', '9'],
    ['Which company makes the iPhone?', 'Apple', 'Samsung', 'Google', 'Nokia'],
    ['What is the square root of 81?', '9', '8', '7', '18'],
    ['About how many weeks are in a year?', '52', '48', '50', '56'],
    ['In which ocean did the Titanic sink?', 'Atlantic', 'Pacific', 'Indian', 'Arctic'],
    ['What does "www" stand for in a web address?', 'World Wide Web', 'Wide Web World', 'World Web Wire', 'Web World Wide'],
    ['Which is the largest country by area?', 'Russia', 'Canada', 'China', 'USA'],
    ['How many teeth does an adult usually have?', '32', '28', '30', '36'],
    ['What is 15% of 200?', '30', '15', '20', '45'],
    ['Which metal is liquid at room temperature?', 'Mercury', 'Lead', 'Tin', 'Aluminium'],
    ['How many pieces does each player start with in chess?', '16', '12', '18', '20'],
    ['What do you call a word that reads the same backwards, like "level"?', 'Palindrome', 'Anagram', 'Acronym', 'Synonym'],
    ['How many sides does a pentagon have?', '5', '6', '4', '8'],
  ],
  science: [
    ['Sound travels fastest through which of these?', 'Steel', 'Water', 'Air', 'A vacuum'],
    ['Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars'],
    ['Which gas makes up most of the air we breathe?', 'Nitrogen', 'Oxygen', 'Carbon dioxide', 'Argon'],
    ['What is the pH of pure water?', '7', '0', '5', '14'],
    ['What is the chemical symbol for sodium?', 'Na', 'So', 'Sd', 'S'],
    ['What is the chemical symbol for iron?', 'Fe', 'Ir', 'In', 'I'],
    ['Which part of the cell is called its powerhouse?', 'Mitochondria', 'Nucleus', 'Ribosome', 'Vacuole'],
    ['How many chambers does the human heart have?', '4', '2', '3', '6'],
    ['Sunlight helps your skin make which vitamin?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin B12'],
    ['What unit is electrical resistance measured in?', 'Ohms', 'Volts', 'Amps', 'Watts'],
    ['What unit is force measured in?', 'Newtons', 'Joules', 'Pascals', 'Kilograms'],
    ['Who came up with the theory of relativity?', 'Albert Einstein', 'Isaac Newton', 'Charles Darwin', 'Nikola Tesla'],
    ['A whale is what kind of animal?', 'Mammal', 'Fish', 'Reptile', 'Amphibian'],
    ['Which planet has the Great Red Spot?', 'Jupiter', 'Mars', 'Saturn', 'Neptune'],
    ['How many planets are in our solar system?', '8', '9', '7', '10'],
    ['Which blood cells fight infection?', 'White blood cells', 'Red blood cells', 'Platelets', 'Plasma'],
    ['What does DNA stand for?', 'Deoxyribonucleic acid', 'Dinitrogen acid', 'Dual nucleic acid', 'Deoxyribose nitrate'],
    ['What is the smallest bone in the human body?', 'Stapes (in the ear)', 'Femur', 'Patella', 'Radius'],
    ['Which organ filters your blood to make urine?', 'Kidneys', 'Liver', 'Lungs', 'Stomach'],
    ['What tool measures temperature?', 'Thermometer', 'Barometer', 'Odometer', 'Speedometer'],
    ['Which gas is the Sun mostly made of?', 'Hydrogen', 'Oxygen', 'Helium', 'Carbon'],
    ['Diamonds are made of which element?', 'Carbon', 'Silicon', 'Iron', 'Oxygen'],
    ['A light-year measures what?', 'Distance', 'Time', 'Speed', 'Brightness'],
    ['What do plants release during photosynthesis?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Methane'],
    ['Which planet is known as the Morning Star?', 'Venus', 'Mars', 'Jupiter', 'Mercury'],
  ],
  geography: [
    ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
    ['What is the capital of the USA?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    ['Which is the largest country in Africa by area?', 'Algeria', 'DR Congo', 'Sudan', 'Nigeria'],
    ['What is the highest mountain in the world?', 'Mount Everest', 'K2', 'Kilimanjaro', 'Mont Blanc'],
    ['What is the capital of Senegal?', 'Dakar', 'Bamako', 'Banjul', 'Conakry'],
    ['What is the capital of Rwanda?', 'Kigali', 'Kampala', 'Bujumbura', 'Dodoma'],
    ['What is the capital of Ethiopia?', 'Addis Ababa', 'Asmara', 'Nairobi', 'Khartoum'],
    ['What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakech', 'Fez'],
    ['Which country has the most people?', 'India', 'China', 'USA', 'Indonesia'],
    ['Victoria Falls is on which river?', 'Zambezi', 'Nile', 'Congo', 'Limpopo'],
    ['What is the capital of Cameroon?', 'Yaoundé', 'Douala', 'Buea', 'Garoua'],
    ['What is the capital of Brazil?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
    ['Greenland belongs to which country?', 'Denmark', 'Canada', 'Norway', 'Iceland'],
    ['Dubai is in which country?', 'United Arab Emirates', 'Saudi Arabia', 'Qatar', 'Oman'],
    ['What is the official capital of Côte d’Ivoire?', 'Yamoussoukro', 'Abidjan', 'Bouaké', 'Accra'],
    ['Which sea lies between Africa and Europe?', 'Mediterranean Sea', 'Red Sea', 'Black Sea', 'Caspian Sea'],
    ['What is the capital of Zimbabwe?', 'Harare', 'Bulawayo', 'Lusaka', 'Gaborone'],
    ['What is the capital of Germany?', 'Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
    ['What is the capital of Spain?', 'Madrid', 'Barcelona', 'Seville', 'Valencia'],
    ['Which is the largest island in the world?', 'Greenland', 'Madagascar', 'Borneo', 'New Guinea'],
    ['What is the capital of Togo?', 'Lomé', 'Cotonou', 'Accra', 'Ouagadougou'],
    ['What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Naples'],
    ['Mount Fuji is in which country?', 'Japan', 'China', 'South Korea', 'Nepal'],
    ['What is the capital of Uganda?', 'Kampala', 'Entebbe', 'Kigali', 'Juba'],
    ['Which country has the most pyramids?', 'Sudan', 'Egypt', 'Mexico', 'Peru'],
  ],
  movies: [
    ['Which film won Best Picture at the 2024 Oscars?', 'Oppenheimer', 'Barbie', 'Poor Things', 'Killers of the Flower Moon'],
    ['Which film won Best Picture at the 2025 Oscars?', 'Anora', 'The Brutalist', 'Conclave', 'Wicked'],
    ['Who played Barbie in the 2023 film?', 'Margot Robbie', 'Emma Stone', 'Florence Pugh', 'Zendaya'],
    ['Wicked (2024) stars Cynthia Erivo and which singer?', 'Ariana Grande', 'Selena Gomez', 'Dua Lipa', 'Olivia Rodrigo'],
    ['Who directed Titanic?', 'James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'],
    ['Who stars in and co-directed "A Tribe Called Judah"?', 'Funke Akindele', 'Genevieve Nnaji', 'Omotola Jalade', 'Mercy Johnson'],
    ['Who directed King of Boys?', 'Kemi Adetiba', 'Kunle Afolayan', 'Funke Akindele', 'Niyi Akinmolayan'],
    ['Peter Parker is which superhero?', 'Spider-Man', 'Batman', 'Iron Man', 'Superman'],
    ['What is the cowboy’s name in Toy Story?', 'Woody', 'Buzz', 'Rex', 'Jessie'],
    ['Who played Captain Jack Sparrow?', 'Johnny Depp', 'Orlando Bloom', 'Brad Pitt', 'Tom Cruise'],
    ['What are the blue people in Avatar called?', 'Na’vi', 'Kree', 'Ewoks', 'Elves'],
    ['Which film has the line "I’ll be back"?', 'The Terminator', 'Rocky', 'Die Hard', 'Predator'],
    ['In Friends, which character is a palaeontologist?', 'Ross', 'Chandler', 'Joey', 'Monica'],
    ['What is Thor’s hammer called?', 'Mjolnir', 'Stormbreaker', 'Excalibur', 'Gungnir'],
    ['Bollywood is the film industry of which country?', 'India', 'Pakistan', 'Bangladesh', 'Sri Lanka'],
    ['Who voices Elsa in Frozen?', 'Idina Menzel', 'Kristen Bell', 'Mandy Moore', 'Anna Kendrick'],
    ['Which animated film follows a girl named Riley and her emotions?', 'Inside Out', 'Coco', 'Up', 'Soul'],
    ['What is the name of the clownfish in Finding Nemo who is Nemo’s dad?', 'Marlin', 'Dory', 'Gill', 'Bruce'],
    ['Which actor played Iron Man in the Marvel films?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
    ['Which series is about the Shelby family in Birmingham?', 'Peaky Blinders', 'The Crown', 'Bridgerton', 'Sherlock'],
    ['Which streaming service makes Squid Game?', 'Netflix', 'Prime Video', 'Disney+', 'Apple TV+'],
    ['In Harry Potter, which house is Harry in?', 'Gryffindor', 'Slytherin', 'Ravenclaw', 'Hufflepuff'],
    ['Which film franchise features Dominic Toretto?', 'Fast & Furious', 'Mission: Impossible', 'John Wick', 'Transformers'],
    ['What colour is Shrek?', 'Green', 'Blue', 'Brown', 'Grey'],
    ['Which Disney princess has a pet tiger named Rajah?', 'Jasmine', 'Mulan', 'Pocahontas', 'Moana'],
  ],
  sports: [
    ['Who has won the most Ballon d’Or awards?', 'Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'],
    ['Who won the 2024 Ballon d’Or?', 'Rodri', 'Vinícius Júnior', 'Jude Bellingham', 'Erling Haaland'],
    ['Who won the 2025 Ballon d’Or?', 'Ousmane Dembélé', 'Lamine Yamal', 'Mohamed Salah', 'Kylian Mbappé'],
    ['Who was named African Footballer of the Year for 2024?', 'Ademola Lookman', 'Victor Osimhen', 'Mohamed Salah', 'Achraf Hakimi'],
    ['Which city hosted the 2024 Olympics?', 'Paris', 'Tokyo', 'Los Angeles', 'London'],
    ['Which countries are hosting the 2026 FIFA World Cup?', 'USA, Canada and Mexico', 'Qatar', 'Brazil and Argentina', 'Spain and Portugal'],
    ['Who did the Super Falcons beat in the 2024 WAFCON final, played in July 2025?', 'Morocco', 'South Africa', 'Zambia', 'Ghana'],
    ['What is the nickname of Nigeria’s women’s football team?', 'Super Falcons', 'Super Eagles', 'Flying Eagles', 'Golden Eaglets'],
    ['What is the 100 m world record?', '9.58 seconds', '9.69 seconds', '9.72 seconds', '9.49 seconds'],
    ['Which club has won the most Champions League titles?', 'Real Madrid', 'AC Milan', 'Bayern Munich', 'Liverpool'],
    ['What colour card sends a footballer off?', 'Red', 'Yellow', 'Blue', 'Green'],
    ['How many Grand Slam tournaments are there in tennis each year?', '4', '3', '5', '6'],
    ['How many players does each cricket team field?', '11', '9', '10', '12'],
    ['Which sport is played at the Tour de France?', 'Cycling', 'Running', 'Motor racing', 'Horse racing'],
    ['How many minutes are in a regular football match?', '90', '80', '100', '120'],
    ['In which sport do you hit a home run?', 'Baseball', 'Cricket', 'Golf', 'Hockey'],
    ['How high is a basketball hoop?', '10 feet (3.05 m)', '8 feet (2.44 m)', '12 feet (3.66 m)', '9 feet (2.74 m)'],
    ['Basketball was invented in which country?', 'USA', 'Canada', 'England', 'France'],
    ['How many points is a free throw worth in basketball?', '1', '2', '3', '0.5'],
    ['Which country has won the most Africa Cup of Nations titles?', 'Egypt', 'Cameroon', 'Ghana', 'Nigeria'],
    ['In darts, what is the highest score with one dart?', '60', '50', '40', '100'],
    ['In bowling, what is knocking all pins down with the first ball called?', 'A strike', 'A spare', 'A split', 'A turkey'],
    ['How long is an Olympic swimming pool?', '50 m', '25 m', '100 m', '75 m'],
    ['Which boxer was known as "The Greatest"?', 'Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Joe Frazier'],
    ['In archery, what colour is the centre ring of the target?', 'Gold', 'Red', 'Blue', 'Black'],
  ],
  food: [
    ['Zobo is made from which flower?', 'Hibiscus', 'Rose', 'Sunflower', 'Lily'],
    ['Kunu is a drink made mainly from what?', 'Millet', 'Cocoa', 'Coffee', 'Oranges'],
    ['What is Chapman?', 'A drink', 'A soup', 'A snack', 'A bread'],
    ['Palm wine comes from what?', 'Palm tree sap', 'Palm kernels', 'Coconut milk', 'Grapes'],
    ['Egusi comes from the seeds of which plant?', 'Melon', 'Pumpkin', 'Sunflower', 'Sesame'],
    ['What is the main ingredient in pesto?', 'Basil', 'Spinach', 'Parsley', 'Mint'],
    ['Raisins are dried what?', 'Grapes', 'Plums', 'Cherries', 'Figs'],
    ['What makes chillies hot?', 'Capsaicin', 'Caffeine', 'Citric acid', 'Gluten'],
    ['Oranges are best known for which vitamin?', 'Vitamin C', 'Vitamin A', 'Vitamin D', 'Vitamin K'],
    ['Croissants are most associated with which country?', 'France', 'Italy', 'Belgium', 'Austria'],
    ['Kimchi comes from which country?', 'Korea', 'Japan', 'China', 'Vietnam'],
    ['Popcorn is made from which grain?', 'Corn', 'Rice', 'Wheat', 'Barley'],
    ['Which fruit has its seeds on the outside?', 'Strawberry', 'Raspberry', 'Kiwi', 'Banana'],
    ['Which country is the biggest producer of cocoa beans?', 'Côte d’Ivoire', 'Ghana', 'Nigeria', 'Brazil'],
    ['Ofada rice is usually served with what?', 'Ayamase (green pepper stew)', 'Egusi', 'Okra soup', 'Custard'],
    ['Tuwo shinkafa is made from what?', 'Rice', 'Yam', 'Cassava', 'Beans'],
    ['Amala is made from what?', 'Yam flour', 'Rice flour', 'Wheat flour', 'Corn starch'],
    ['Which soup is made with bitter leaf?', 'Ofe onugbu', 'Edikang ikong', 'Banga', 'Afang'],
    ['Banga soup is made from what?', 'Palm fruit', 'Melon seeds', 'Okra', 'Groundnuts'],
    ['What gives jollof rice its red-orange colour?', 'Tomatoes and peppers', 'Turmeric', 'Saffron', 'Beetroot'],
    ['What is the main ingredient of a French fry?', 'Potato', 'Yam', 'Plantain', 'Cassava'],
    ['Which drink is made from fermented tea?', 'Kombucha', 'Kefir', 'Kvass', 'Kunu'],
    ['What is sushi rice seasoned with?', 'Vinegar', 'Lemon juice', 'Soy sauce', 'Coconut milk'],
    ['Which country gave us tacos?', 'Mexico', 'Spain', 'Brazil', 'Peru'],
    ['What is dried plantain flour used to make?', 'Plantain amala (elubo ogede)', 'Puff-puff', 'Chin chin', 'Akara'],
  ],
  naija: [
    ['Who was Nigeria’s first President?', 'Nnamdi Azikiwe', 'Abubakar Tafawa Balewa', 'Obafemi Awolowo', 'Ahmadu Bello'],
    ['Who was Nigeria’s first Prime Minister?', 'Abubakar Tafawa Balewa', 'Nnamdi Azikiwe', 'Ahmadu Bello', 'Obafemi Awolowo'],
    ['In what year did Abuja officially become Nigeria’s capital?', '1991', '1976', '1985', '1999'],
    ['Who has been Nigeria’s President since 2023?', 'Bola Ahmed Tinubu', 'Muhammadu Buhari', 'Atiku Abubakar', 'Goodluck Jonathan'],
    ['What is Nigeria’s national motto?', 'Unity and Faith, Peace and Progress', 'One Nation, One Destiny', 'Peace and Unity', 'Faith and Freedom'],
    ['Zuma Rock is in which state?', 'Niger', 'Kogi', 'Plateau', 'FCT'],
    ['Olumo Rock is in which city?', 'Abeokuta', 'Ibadan', 'Osogbo', 'Akure'],
    ['How many local government areas does Nigeria have?', '774', '736', '800', '668'],
    ['Which is Nigeria’s largest state by area?', 'Niger', 'Borno', 'Kano', 'Lagos'],
    ['Which country is Nigeria’s great jollof rival?', 'Ghana', 'Senegal', 'Cameroon', 'Sierra Leone'],
    ['Who wrote "Half of a Yellow Sun"?', 'Chimamanda Ngozi Adichie', 'Chinua Achebe', 'Buchi Emecheta', 'Sefi Atta'],
    ['The Third Mainland Bridge is in which city?', 'Lagos', 'Port Harcourt', 'Abuja', 'Onitsha'],
    ['Fela Kuti pioneered which genre?', 'Afrobeat', 'Highlife', 'Jùjú', 'Fuji'],
    ['The Calabar Carnival happens in which state?', 'Cross River', 'Akwa Ibom', 'Rivers', 'Bayelsa'],
    ['Who founded the Dangote Group?', 'Aliko Dangote', 'Mike Adenuga', 'Femi Otedola', 'Tony Elumelu'],
    ['In what year did Ghana gain independence?', '1957', '1960', '1962', '1966'],
    ['Which African country was never colonised?', 'Ethiopia', 'Kenya', 'Morocco', 'Ghana'],
    ['What is South Africa’s currency?', 'Rand', 'Naira', 'Shilling', 'Pula'],
    ['Mansa Musa ruled which empire?', 'Mali Empire', 'Songhai Empire', 'Oyo Empire', 'Ghana Empire'],
    ['Which language is widely spoken across East Africa?', 'Swahili', 'Hausa', 'Amharic', 'Zulu'],
    ['What is the highest mountain in Africa?', 'Kilimanjaro', 'Mount Kenya', 'Mount Cameroon', 'Ras Dashen'],
    ['Which Nigerian city is famous for its ancient walls and dye pits?', 'Kano', 'Kaduna', 'Jos', 'Ilorin'],
    ['Who was the first African woman to win the Nobel Peace Prize?', 'Wangari Maathai', 'Ellen Johnson Sirleaf', 'Leymah Gbowee', 'Graça Machel'],
    ['Which Nigerian state is called the "Centre of Excellence"?', 'Lagos', 'Ogun', 'Oyo', 'Rivers'],
    ['Which river is the longest in West Africa?', 'Niger', 'Volta', 'Senegal', 'Benue'],
  ],
};
