// Quiz Duel question bank. Each entry: [question, correct answer, wrong, wrong, wrong].
import { MUSIC, MORE } from './trivia-more.js';

export const CATEGORIES = {
  general: {
    name: 'General knowledge', icon: 'ph-lightbulb', tone: 'indigo',
    q: [
      ['How many continents are there?', '7', '5', '6', '8'],
      ['Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury'],
      ['How many minutes are in a full day?', '1,440', '1,240', '1,340', '1,540'],
      ['What is the largest ocean on Earth?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
      ['How many sides does a hexagon have?', '6', '5', '7', '8'],
      ['Which is the tallest animal?', 'Giraffe', 'Elephant', 'Ostrich', 'Camel'],
      ['What colour do you get by mixing blue and yellow?', 'Green', 'Purple', 'Orange', 'Brown'],
      ['Which language has the most native speakers?', 'Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
      ['How many players does a football team have on the pitch?', '11', '10', '9', '12'],
      ['What is the hardest natural substance?', 'Diamond', 'Gold', 'Iron', 'Quartz'],
      ['Which is the shortest month of the year?', 'February', 'April', 'June', 'November'],
      ['What is the capital of Japan?', 'Tokyo', 'Kyoto', 'Osaka', 'Seoul'],
      ['How many hours are in a week?', '168', '148', '156', '172'],
      ['Which instrument has 88 keys?', 'Piano', 'Guitar', 'Violin', 'Harp'],
      ['At what temperature does water freeze in Celsius?', '0°C', '32°C', '10°C', '-10°C'],
    ],
  },
  science: {
    name: 'Science', icon: 'ph-atom', tone: 'teal',
    q: [
      ['Which gas do plants take in from the air?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Hydrogen'],
      ['What is H₂O better known as?', 'Water', 'Salt', 'Hydrogen peroxide', 'Oxygen'],
      ['How many bones are in the adult human body?', '206', '196', '216', '226'],
      ['What is the closest star to Earth?', 'The Sun', 'Proxima Centauri', 'Sirius', 'Polaris'],
      ['Which part of a human cell holds most of its DNA?', 'Nucleus', 'Ribosome', 'Cell membrane', 'Cytoplasm'],
      ['What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go'],
      ['Which organ pumps blood around the body?', 'Heart', 'Lungs', 'Liver', 'Kidney'],
      ['What force keeps us on the ground?', 'Gravity', 'Magnetism', 'Friction', 'Inertia'],
      ['At sea level, water boils at what temperature in Celsius?', '100°C', '90°C', '110°C', '120°C'],
      ['Which is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth'],
      ['What do bees make from nectar?', 'Honey', 'Silk', 'Syrup', 'Jam'],
      ['Roughly how fast does light travel?', '300,000 km per second', '3,000 km per second', '30,000 km per second', '3 million km per second'],
      ['Which blood type is known as the universal donor?', 'O negative', 'AB positive', 'A positive', 'B negative'],
      ['What is the largest organ of the human body?', 'Skin', 'Liver', 'Brain', 'Heart'],
      ['Which element has the chemical symbol O?', 'Oxygen', 'Osmium', 'Gold', 'Zinc'],
    ],
  },
  geography: {
    name: 'Geography', icon: 'ph-globe-hemisphere-east', tone: 'olive',
    q: [
      ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Ibadan', 'Kano'],
      ['What is the longest river in Africa?', 'Nile', 'Congo', 'Niger', 'Zambezi'],
      ['What is the capital of Ghana?', 'Accra', 'Kumasi', 'Tamale', 'Lomé'],
      ['What is the largest desert in Africa?', 'Sahara', 'Kalahari', 'Namib', 'Gobi'],
      ['What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kampala', 'Addis Ababa'],
      ['Mount Kilimanjaro is in which country?', 'Tanzania', 'Kenya', 'Uganda', 'Ethiopia'],
      ['What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice'],
      ['Which is the smallest continent?', 'Australia', 'Europe', 'Antarctica', 'South America'],
      ['Which country is shaped like a boot?', 'Italy', 'Spain', 'Greece', 'Portugal'],
      ['What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Giza', 'Luxor'],
      ['Which ocean lies along the west coast of Africa?', 'Atlantic', 'Indian', 'Pacific', 'Arctic'],
      ['Where does the Niger River meet the sea?', 'Gulf of Guinea', 'Mediterranean Sea', 'Red Sea', 'Indian Ocean'],
      ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
      ['Marrakech is a city in which country?', 'Morocco', 'Algeria', 'Tunisia', 'Egypt'],
      ['Lake Victoria is shared by Kenya, Uganda and which country?', 'Tanzania', 'Rwanda', 'Ethiopia', 'Malawi'],
    ],
  },
  music: {
    name: 'Music', icon: 'ph-music-notes', tone: 'plum', blurb: 'Only the latest: 2024 to now',
    q: MUSIC,
  },
  movies: {
    name: 'Movies and TV', icon: 'ph-film-slate', tone: 'rust',
    q: [
      ['Who played T’Challa in Black Panther (2018)?', 'Chadwick Boseman', 'Michael B. Jordan', 'Daniel Kaluuya', 'Idris Elba'],
      ['In Frozen, which character sings "Let It Go"?', 'Elsa', 'Anna', 'Olaf', 'Moana'],
      ['Which film features the character Jack Dawson?', 'Titanic', 'Avatar', 'The Notebook', 'Inception'],
      ['What is Nigeria’s film industry called?', 'Nollywood', 'Bollywood', 'Kollywood', 'Ghallywood'],
      ['Which school does Harry Potter attend?', 'Hogwarts', 'Durmstrang', 'Beauxbatons', 'Ilvermorny'],
      ['Who directed Jurassic Park?', 'Steven Spielberg', 'James Cameron', 'George Lucas', 'Ridley Scott'],
      ['In The Lion King, who is Simba’s father?', 'Mufasa', 'Scar', 'Rafiki', 'Zazu'],
      ['Money Heist was first made in which country?', 'Spain', 'Mexico', 'Italy', 'Argentina'],
      ['What is the name of the snowman in Frozen?', 'Olaf', 'Sven', 'Kristoff', 'Hans'],
      ['Which series features a place called the Upside Down?', 'Stranger Things', 'Dark', 'The OA', 'Wednesday'],
      ['Who plays the title role in the series Wednesday (2022)?', 'Jenna Ortega', 'Millie Bobby Brown', 'Zendaya', 'Florence Pugh'],
      ['King of Boys is a film from which country?', 'Nigeria', 'Ghana', 'South Africa', 'Kenya'],
      ['Squid Game is set in which country?', 'South Korea', 'Japan', 'China', 'Thailand'],
      ['Which film won Best Picture at the Oscars in 2020?', 'Parasite', '1917', 'Joker', 'Green Book'],
      ['Which superhero comes from Wakanda?', 'Black Panther', 'Storm', 'Falcon', 'Cyborg'],
    ],
  },
  sports: {
    name: 'Sports', icon: 'ph-soccer-ball', tone: 'wine',
    q: [
      ['How many players per team are on a basketball court?', '5', '6', '7', '4'],
      ['Which country won the 2022 FIFA World Cup?', 'Argentina', 'France', 'Brazil', 'Croatia'],
      ['"Super Eagles" is the nickname of which national team?', 'Nigeria', 'Ghana', 'Cameroon', 'Senegal'],
      ['Usain Bolt represents which country?', 'Jamaica', 'USA', 'Kenya', 'Trinidad and Tobago'],
      ['How many rings are on the Olympic flag?', '5', '4', '6', '7'],
      ['In tennis, what is a score of zero called?', 'Love', 'Nil', 'Duck', 'Zip'],
      ['Which footballer is nicknamed "CR7"?', 'Cristiano Ronaldo', 'Ronaldinho', 'Ronaldo Nazário', 'Kaká'],
      ['How long is a marathon?', '42.195 km', '40 km', '26 km', '50 km'],
      ['Which sport uses a shuttlecock?', 'Badminton', 'Squash', 'Tennis', 'Table tennis'],
      ['Wimbledon is played in which country?', 'England', 'France', 'USA', 'Australia'],
      ['How many points is a touchdown worth in American football?', '6', '7', '3', '5'],
      ['Who won the Africa Cup of Nations played in early 2024?', 'Ivory Coast', 'Nigeria', 'Senegal', 'Egypt'],
      ['In which sport would you see a slam dunk?', 'Basketball', 'Volleyball', 'Handball', 'Netball'],
      ['How many holes are on a standard golf course?', '18', '9', '12', '21'],
      ['Which country has won the most FIFA World Cups?', 'Brazil', 'Germany', 'Italy', 'Argentina'],
    ],
  },
  food: {
    name: 'Food', icon: 'ph-cooking-pot', tone: 'gold',
    q: [
      ['Sushi comes from which country?', 'Japan', 'China', 'Korea', 'Thailand'],
      ['What is the main ingredient in guacamole?', 'Avocado', 'Peas', 'Cucumber', 'Spinach'],
      ['Which nut is used to make marzipan?', 'Almond', 'Peanut', 'Cashew', 'Walnut'],
      ['Akara is made mainly from what?', 'Beans', 'Yam', 'Cassava', 'Corn'],
      ['Suya is best described as what?', 'Spiced grilled meat', 'Fried fish', 'Bean cake', 'Yam porridge'],
      ['Pizza comes from which country?', 'Italy', 'Greece', 'USA', 'France'],
      ['Tofu is made from what?', 'Soybeans', 'Rice', 'Wheat', 'Milk'],
      ['Which fruit is called the "king of fruits" in Southeast Asia?', 'Durian', 'Mango', 'Jackfruit', 'Pineapple'],
      ['Real Champagne has to come from which country?', 'France', 'Italy', 'Spain', 'Germany'],
      ['Garri is made from what?', 'Cassava', 'Yam', 'Maize', 'Plantain'],
      ['Which is the most expensive spice by weight?', 'Saffron', 'Vanilla', 'Cardamom', 'Cinnamon'],
      ['Moi moi is made mainly from what?', 'Beans', 'Rice', 'Corn', 'Plantain'],
      ['What is the main ingredient in hummus?', 'Chickpeas', 'Lentils', 'Black beans', 'Peas'],
      ['Puff-puff is made from what kind of dough?', 'Flour', 'Rice', 'Plantain', 'Beans'],
      ['Which country is famous for paella?', 'Spain', 'Portugal', 'Mexico', 'Italy'],
    ],
  },
  naija: {
    name: 'Nigeria and Africa', icon: 'ph-flag', tone: 'rose',
    q: [
      ['In what year did Nigeria gain independence?', '1960', '1957', '1963', '1970'],
      ['What is Nigeria’s currency?', 'Naira', 'Cedi', 'Rand', 'Shilling'],
      ['How many states does Nigeria have?', '36', '30', '32', '37'],
      ['Which is Africa’s most populous country?', 'Nigeria', 'Ethiopia', 'Egypt', 'DR Congo'],
      ['What is Ghana’s currency?', 'Cedi', 'Naira', 'Dalasi', 'Kwacha'],
      ['Who was South Africa’s first Black president?', 'Nelson Mandela', 'Thabo Mbeki', 'Jacob Zuma', 'Desmond Tutu'],
      ['What are the colours of Nigeria’s flag?', 'Green and white', 'Green, yellow and red', 'Black and gold', 'Blue and white'],
      ['Which Nigerian won the Nobel Prize in Literature in 1986?', 'Wole Soyinka', 'Chinua Achebe', 'Ben Okri', 'Chimamanda Ngozi Adichie'],
      ['Who wrote Things Fall Apart?', 'Chinua Achebe', 'Wole Soyinka', 'Ngũgĩ wa Thiong’o', 'Buchi Emecheta'],
      ['Lagos State is in which geopolitical zone?', 'South West', 'South South', 'North Central', 'South East'],
      ['Which river gave Nigeria its name?', 'Niger', 'Benue', 'Ogun', 'Cross River'],
      ['The Great Pyramid of Giza is in which country?', 'Egypt', 'Sudan', 'Ethiopia', 'Libya'],
      ['Which country is called the Rainbow Nation?', 'South Africa', 'Kenya', 'Ghana', 'Rwanda'],
      ['Where is the African Union headquartered?', 'Addis Ababa', 'Abuja', 'Nairobi', 'Cairo'],
      ['What is Nigeria’s largest city by population?', 'Lagos', 'Kano', 'Ibadan', 'Abuja'],
    ],
  },
};

for (const [id, extra] of Object.entries(MORE)) CATEGORIES[id].q.push(...extra);
